name: C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - name: ls
      run: ls -R
    - name: run cmake
      run: cmake --help && ls -R
    - name: run cmake 2
      run: mkdir build && cd build
    - name: run cmake 3
      run: ls -R && cd build && ls -R && echo $PWD && cmake .. || cmake
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ./hello_world
